### ISSUE TITLE
Documentation du projet

### ISSUE THREAD

**Issue by Sukaato** [Sukaato/CoinCoins-Insolites-backend#6]
Ajouter de la documentation au projet (https://github.com/Sukaato/CoinCoins-Insolites-backend/community)
- [x] ajout description
- [x] ajout Contributing

**Comment by GwendalPayoux** [comment]
## Description courte ##

Nom : CoinCoins-Insolites-backend
Date de création : 17 décembre 2019

Description: Le projet se présente comme une API backend de l'application CoinCoins Insolites qui permet de référencer une liste de lieux insolites.
